import * as value_getters from "@/components/table/value_getters";

var cols = [
  {
    headerName: "object",
    chartDataType: "none",
    field: "objectid",
    filter: "agTextColumnFilter",
    sortable: true,
    rowGroup: true,
    hide: true,
    enableRowGroup: true,
    flex: 1,
  },
  {
    headerName: "subelem",
    field: "carnumber",
    rowGroup: true,
    hide: true,
    enableRowGroup: true,
    flex: 1,
  },
  {
    headerName: "module",
    field: "bogie",
    rowGroup: true,
    enableRowGroup: true,
    hide: true,
  },
  {
    headerName: "axis",
    field: "axis",
    rowGroup: true,
    enableRowGroup: true,
    hide: true,
    flex: 1,
  },
  {
    headerName: "comp",
    field: "comp",
    rowGroup: true,
    enableRowGroup: true,
    hide: true,
    flex: 1,
  },
  {
    headerName: "algo",
    field: "origin",
    colId: "params",
    hide: false,
    flex: 1,
  },
  {
    headerName: "diagid",
    field: "diagid",
    hide: false,
  },
  {
    headerName: "mileage",
    field: "mileage",
    colId: "mileageCol",
    valueGetter: value_getters.mileageValueGetter,
    cellRendererFramework: "MileageCellRenderer",
    aggFunc: "first",
    maxWidth: 100,
  },
  {
    headerName: "out-of-op",
    field: "origin",
    colId: "outOfOpCol",
    valueGetter: value_getters.outOfOpValueGetter,
    aggFunc: "max",
    cellRendererFramework: "OutOfOperationCellRenderer",
    maxWidth: 100,
  },
  {
    headerName: "action",
    field: "value",
    cellRenderer: "childMessageRenderer",
    colId: "params",
    filter: false,
    maxWidth: 200,
  },
  {
    headerName: "time",
    field: "lastResultTime",
    maxWidth: 200,
  },

  {
    headerName: "available",
    field: "lastResult_HS",
    colId: "available_cnt",
    valueGetter: value_getters.availableValueGetter,
    aggFunc: "sum",
    maxWidth: 100,
  },
  {
    headerName: "expected",
    field: "lastResult_HS",
    colId: "expected_cnt",
    valueGetter: value_getters.expectedValueGetter,
    aggFunc: "sum",
    maxWidth: 100,
  },
  {
    headerName: "%",
    field: "percentage",
    valueGetter: value_getters.percentageValueGetter,
    maxWidth: 100,
    cellRendererFramework: "PercentageCellRenderer",
  },
  {
    headerName: "reliable",
    aggFunc: "min",
    colId: "reliableCol",
    valueGetter: value_getters.reliableValueGetter,
    maxWidth: 150,
    cellRendererFramework: "ReliableCellRenderer",
  },
  {
    headerName: "max(HS)",
    field: "lastResult_HS",
    valueGetter: value_getters.maxHSValueGetter,
    aggFunc: "max",
    width: 120,
    sortable: true,
    filter: "agTextColumnFilter",
    maxWidth: 150,
  },
];

export { cols };
